### ISSUE TITLE
Possible integration tests

### ISSUE THREAD

**Issue by mlinksva** [github/balanced-employee-ip-agreement#30]
I don't think integration tests are _necessary_ for this project, but here are some that could be nice:

- [x] Links in README and agreement work
- [ ] Statute texts in Exhibit A match texts found at reference links (#28 could complicate)
- [ ] Updates to agreement get new version in accordance with #27 outcome
- [ ] Updates to agreement don't make readability scores significantly worse
- [ ] Spelling and grammar checks

Non-automated versions can be documented with #27

**Comment by misteraverin** [comment]
@mlinksva suggestion: check spelling and punctuation with Travis

**Comment by mlinksva** [comment]
@misteraverin thanks, added above.

**Comment by kemitchell** [comment]
Prior art, in case it saves you time: https://github.com/npm/policies/blob/master/.travis.yml.

**Comment by mlinksva** [comment]
#74 addresses the first item, link checking. The others would be welcome but unlikely to get to them, so closing.
