### ISSUE TITLE
Employees can't verify "prospective Company product[s] or service[s]"

### ISSUE THREAD

**Issue by vitorio** [github/balanced-employee-ip-agreement#38]
From my own negotiated IP agreement with my current employer, they included wording similar to ¶1(i):

> The IP (i) related to an existing or prospective Company product or service at the time you developed, invented, or created it,

Except in the smallest of companies, it's probably impossible for an individual employee to know what might be a "prospective" Company product or service at any given time.  In my agreement, this was changed to something like:

> The IP (i) related to an existing or _demonstrably_ prospective Company product or service _of which you had knowledge_ at the time you developed, invented, or created it,

A related clause also required me to have been directly involved with the existing or demonstrably prospective product or service in the two years prior.

**Comment by mlinksva** [comment]
@vitorio while it may take awhile to respond/resolve in the context of BEIPA (to be documented, see #41) I wanted to thank you for filing this and relating your direct experience. This is really valuable and I want to encourage others to share how they've arrived at more 'balanced' terms (from employee or company 'sides', or preferably with understanding of both).

**Comment by kemitchell** [comment]
This change occurred to me as well, on a general read. A "knowledge qualifier" is the obvious lawyer solution. Companies might also want to include publicly announced products---products the employee very well could or even should know about, but may not for whatever reason.

**Comment by gregorynicholas** [comment]
@vitorio was a "standard" ip assignment document initially presented to you? and did you propose use of this agreement?

**Comment by vitorio** [comment]
@gregorynicholas They provided me their own; I don't know the provenance of it.  This would have been nearly five years ago and the BIPA didn't exist then. I negotiated the changes with them based on advice from my own legal counsel.

**Comment by mlinksva** [comment]
We did end up adding a knowledge qualifier in https://github.com/github/balanced-employee-ip-agreement/commit/c0a5629b8a29f96549b1d5add8399b6a1c0ac9f1 (part of forthcoming v2) -- though not to the language directly related to that mentioned in the issue comment -- importantly, for related to the business IP created outside of the scope of employment, the company gets a non-exclusive license rather than ownership
