### ISSUE TITLE
Ambiguous as to when employee acts "as [the employer's] employee or contractor"

### ISSUE THREAD

**Issue by copiesofcopies** [github/balanced-employee-ip-agreement#39]
The BEIPA says that "[t]he Company owns any IP... that you create, or help create _as its employee or contractor_." It is unclear whether this intended to cover any work done during the term of the employee's employment (and which satisfies an "additional condition"), or only work performed within the scope of the employee's responsibilities to the employer.

**Comment by mlinksva** [comment]
@copiesofcopies thanks for the definite article vote. Also the question, which'll take some time to answer, see #41.

**Comment by mlinksva** [comment]
I believe this is addressed in v2:

> The Company owns any IP ("Company IP") that you create, or help create, during the term of your employment or contract work, _within the scope of your employment or contract_.
