### ISSUE TITLE
Incorrect reference to previous section

### ISSUE THREAD

**Issue by jryans** [github/balanced-employee-ip-agreement#43]
In Section 2, the text appears define what the Company _does not_ own by referencing what the Company _does_ own, saying "the conditions above in Section 2", but that's the same section we're currently in. I assume it should say "the conditions above in Section 1".

**Comment by mlinksva** [comment]
Yep. This will be fixed when #37 is merged.

**Comment by jryans** [comment]
Oops, I looked through open issues but not PRs... 😅 Thanks!
