### ISSUE TITLE
Move generated pdf/odt/docx out of repo into releases

### ISSUE THREAD

**Issue by mlinksva** [github/balanced-employee-ip-agreement#45]
I added (#29 and #34) these to the repo just before making public after reading an item on a checklist for releasing new open source projects that asks if distribution with a convenient and standard mechanism (such as a package repository) has been set up. There's no appropriate package repository for BEIPA, but pdf/odt/docx are pretty "convenient and standard" (for various meanings of the terms, or not). But there's no reason for these generated artifacts to be in the repo rather than [release](https://help.github.com/categories/releases/) assets. Right?

**Comment by kemitchell** [comment]
I don't include build products in my repos.  It's not too hard to set up a Makefile to put everything for a release in a `build` directory.  If you end up doing a lot of releases, you can automate release with Travis and friends.

For the kitchen sink---Debian `sudo apt-get install`s on Travis, release, Google Drive integration---see https://github.com/Ironsides/ironsides/blob/master/.travis.yml.

I'd actually recommend you keep it much simpler than that.  There just aren't that many release of these kinds of projects.  But getting build products out of Git---a combination of automated build and `.gitignore` for the products---has immediate advantages.  It keeps the commits clean.  Source Markdown and the other format sitting right next to it won't go out of sync in the working tree.

**Comment by kemitchell** [comment]
Almost forgot the shameless plug!

I have written, and host, something pretty close to a package repository for legal contracts: https://commonform.org/publishers. The web interface there will generate .docx readily, but it's not hard to put a link in a release with other build products, as well, e.g.:

https://github.com/kemitchell/software-service-terms/releases/tag/1e6d

**Comment by mlinksva** [comment]
Yep, noticed commonform elsewhere. Keeping an eye on it for future projects, and perhaps this one at some point.
