### ISSUE TITLE
Outside Work: Obligations or Suggestions?

### ISSUE THREAD

**Issue by kemitchell** [github/balanced-employee-ip-agreement#47]
Are the terms of "Your contributions to non-Company projects" intended to create binding obligations, or just state preferred company practice?  The company could fire for failure to abide by them, but of course in work-for-hire situations, they can fire you anyway.

**Comment by mlinksva** [comment]
Thanks for asking nicely what's the point of the section on Your contributions to non-Company projects. 😄

The reason for including the section is that the IP agreement is the defining agreement on IP the employee creates, but in a modern company employee assignment to the employer is not the only thing that defines the role of IP for what the employee creates -- collaboration with third parties, often through open source projects, is also a defining characteristic of knowledge work. So we think it's worthwhile for both employees and employers to recognize this other defining characteristic in the defining agreement between them, to set the tone for smooth operation and a happy relationship that includes third parties, from the beginning.

Happy to read feedback on whether the section can be improved toward this goal. Closing for now as I don't think there's an immediate action item from this.

**Comment by kemitchell** [comment]
Any company I can imagine using this agreement, or one like it, would also have an Open Source policy covering use and release. That kind of policy is company-wide, primarily concerned with process, like approval committees, and revisited regularly. Individual IP agreements, on the other hand, are per-employee, primarily concerned with legal ownership, and revised rarely, if ever, for a single employee.

If the language of the section is intended to be a legal no-op, at a minimum, it should say so. Alas, it is very hard to say nothing in a legal document---especially with so many words---without affecting interpretation of other terms, or eliciting awkward questions. Better to strike it from the IP agreement and relocate to the top of the OSS policy.  If there are lots of non-Company projects going on, send out regular e-mails---say, once a quarter---reminding folks to be in touch, and with whom, if that's not glaringly obvious.  You'll get more eyes than burying it in the IP terms they sign on day one.
