### ISSUE TITLE
Further Assurances by any other name...

### ISSUE THREAD

**Issue by kemitchell** [github/balanced-employee-ip-agreement#48]
> 7\. **IP protection.**  The Company might someday need to show the work that went into the development of IP that it uses or has used, or to make government filings to establish that it owns the IP or has rights over it.  To help in those situations, you agree not to destroy any records you maintain relating to the development of any Company IP or IP under License (together, "All IP"), and, if the Company asks, to provide those records to the Company.

Is the obligation to keep and provide records intended to apply to work on, say, a personal open-source project incorporated into company products that the employee continues to develop after leaving the company?  That could get very sticky.

> You agree to help the Company secure and defend its rights in All IP, including after you leave the Company.  For your help the Company will compensate you at a reasonable rate.

While the employee is employed at the company, is this compensation intended to be _in addition_ to regular employee compensation?

In the case of IP under License, is the thought here to provide help defending the company from a suit for infringement of the IP, say if the employee assigned IP under license to another company that brought suit for infringement?  Wouldn't the documented License suffice?

> If the Company is unable to secure your help, you authorize the Company to act on your behalf (as your agent and attorney-in-fact) in securing all rights related to All IP.

If the intent is perfection of _ownership_ rights, like copyright registration ahead of an infringement suit, why is this for All IP, as opposed to just Company IP?  Won't the written license grant of the IP agreement itself provide all the necessary evidence for IP under License?

**Comment by mlinksva** [comment]
Thanks for this (and for/below also applies to your #46 #47)!

As [stated](https://github.com/github/balanced-employee-ip-agreement/blob/e8a2fe7d122035ce531fe0dd1297b351032dc82b/CONTRIBUTING.md#help-wanted) it'll probably take some time to reply or make related changes.

**Comment by mlinksva** [comment]
693958eec36d1b40fc27fbd4fb4021b983608879 (part of #44) should address all of the points raised here. Thanks @kemitchell and feel free to reopen or comment if you think not.
