### ISSUE TITLE
What is Section 2?

### ISSUE THREAD

**Issue by mottosso** [github/balanced-employee-ip-agreement#56]
Hi github,

In paragraph 2, there is mention of "Section 2" but I can't figure out what it is in reference to.

> 2. What the Company doesn't own. If you create IP that doesn't fit into one of the categories listed above, the Company doesn't own it. In other words, the Company doesn't own any concepts, designs, developments, discoveries, ideas, improvements, trade secrets, or any works of authorship that you develop, invent or create that do not meet any of the conditions above in Section 2.

Help!

**Comment by mlinksva** [comment]
It's a bug, it should say Section 1.

I shouldn't have let that linger in master, will pull in an existing fix shortly and leave this open until then.

Thanks!

**Comment by mottosso** [comment]
Thanks @mlinksva!
