### ISSUE TITLE
Copyright infringement by employee under BEIPA

### ISSUE THREAD

**Issue by GnorTech** [github/balanced-employee-ip-agreement#58]
I believe GitHub employee @zcbenz 's work on [libyue](https://github.com/yue/yue) is bound with BEIPA so I'm raise the issue here. 

What if employee violates copyright laws when he/she is doing work under BEIPA? Does the document say anything about this? Should the employer be responsible for the violation if they get sued? It would be better if the FAQ section could include this.

@zcbenz clearly violates copyright laws in his work, see [the issue](https://github.com/yue/help/issues/4) and [Hacker News discussion](https://news.ycombinator.com/item?id=15220169)

Note that he also did this in the past in work time for GitHub official project Electron, see the complaint here:  https://github.com/electron/electron/issues/5172#issuecomment-210697670

CC @hoolio @mlinksva @defunkt @nathansobo

**Comment by jessephus** [comment]
We aren't going to comment on internal company matters.
