### ISSUE TITLE
Length of IP assignment

### ISSUE THREAD

**Issue by sunseasnow** [github/balanced-employee-ip-agreement#59]
Hi. Not a lawyer. Looking at using Beipa in EU, and it looks like an IP assignment is valid in certain EU countries only if the length of assignment is specified. So, at the end of section 1), I would add: ", indefinitely (or alternatively the maximum period allowable by law in case a specific period needs to be assigned as per applicable law or 100 years if that maximum is not specified by law).

**Comment by BPiVcarD** [comment]
#

**Comment by mlinksva** [comment]
Hi, thanks for the suggestion. I'm going to close as we'd address this holistically with any other changes necessary to support various EU jurisdictions, for which there's a general open issue at #53.

However, more info would be helpful when we get to that. If you're inclined, would love to know which certain EU countries are you thinking of. Even better, pointers to one or more of the relevant law, analysis of the relevant law (academic, policy, or practice-oriented), and existing agreements addressing that law.
