### ISSUE TITLE
Sounds pretty hypocritical

### ISSUE THREAD

**Issue by rattacresh** [github/balanced-employee-ip-agreement#63]
> To the extent allowable by law, employers get control over everything employees create while employed, 24/7

How is that different in any practical terms from

> The Company owns any IP ("Company IP") that you create, or help create as its employee or contractor, but only if it meets one or more of these additional conditions: The IP was (i) related to an ... prospective Company product"

Everything that the company is honestly interested in is related to a prospective Company product. So at best, this might protect you from bad faith, ie., the company claiming your IP to be theirs despite not actually interested in developing it into one of its products. But try to prove that.

> and sometimes even to gain control over what former employees create through "non-compete" terms. For an overview, see The New Cognitive Property: Human Capital Law and the Reach of Intellectual Property.

How is that different in any practical terms from 7 ("IP protection")?

If you switch from employee A to employee B and develop a product for B, this allows A to file a patent on that product, claiming you developed the core idea during your old contract. 7 forces you to support that claim. In particular, it isn't possible for you to claim that the patent is invalid. This is, in disguise,  exactly one of those "non-compete" terms criticized by "The New Cognitive Property".

All in all, this is a hypocritical agreement. It it guilty of exactly those sins which it criticizes.

**Comment by balupton** [comment]
I also picked up on this too. The v2 proposal seems to do better on this.

> What the Company owns. The Company owns any IP ("Company IP") that you create, or help create as its employee or contractor, but only if it meets one or more of these additional conditions: The IP was (i) related to an existing or prospective Company product or service at the time you developed, invented, or created it, (ii) developed for use by the Company, or (iii) developed or promoted with existing Company IP or with the Company's endorsement. You hereby grant and assign, and will grant and assign, to the Company all rights and interests in all Company IP.

> Contribution of your IP to Company projects. If you include your own IP – such as IP you created prior to working for the Company – into a Company product or service, it's still yours, of course, but you grant the Company a non-exclusive, irrevocable, fully paid-up, royalty-free, perpetual, sublicensable, transferable, worldwide license to use it without restriction in any way or implementation, in modified form, or as is, by itself, or incorporated into another product or service ("License"). If you include your name in any project over which the Company would have rights under this Agreement, such as in a copyright notice or a comment in code or documentation, then the License covers the rights associated with that use of your name as well.

As it currently stands, those two above parts, seem like a company could claim license to any IP for something they planned or that they entered into, while stealing IP from me.

However, I think that the **as its employee or contractor** and the **you include** parts are the defence against this, that make it ok.

**Comment by mlinksva** [comment]
> This is, in disguise, exactly one of those "non-compete" terms criticized by "The New Cognitive Property".

Exactly, no. It's conceivable that a new employer might be less interested in hiring you due to minimal obligations to help secure a previous employer's IP. Would love to read evidence of that happening. The non-compete terms criticized in that great article typically allow a previous employer to prevent you from working for a competitor. This happens frequently and has been the subject of much litigation. Please read the paper! 😄 

> The other aspect to BEIPA that is concerning on this front is that it seems to heavily rely on state specific laws to constrain itself.

No, it doesn't. It goes beyond what any U.S. state specific laws require, in favor of the employee. There seems to be a similar misunderstanding here as in #51 which I also belatedly looked at again and closed.
