### ISSUE TITLE
Violates the idea-expression divide

### ISSUE THREAD

**Issue by balupton** [github/balanced-employee-ip-agreement#64]
> "Company IP" includes concepts, designs, developments, discoveries, ideas, improvements, inventions, trade secrets, trademarks, and works of authorship.

That part still seems to violate the [idea-expression divide](https://en.wikipedia.org/wiki/Idea–expression_divide) (excerpt below), as only expressions of ideas are copyrightable, but the quoted clause is claiming ownership of more than just expressions.

> Additionally, in Mazer v. Stein, 347 U.S. 201, 217 (1954), the Supreme Court stated "Unlike a patent, a copyright gives no exclusive right to the art disclosed; protection is given only to the expression of the idea—not the idea itself."

To address this, BEIPA can make its state specific employee protections available to all, such as Californa's protections of employee inventions, such that all employee's globally share equal protections. As well as stating explicitly:

> Ideas including concepts and strategies, are not copyrightable, due to the idea-expression divide, with only their particular expression at a company being copyrightable.

As right now with BEIPA:

- It is written to violate the idea-expression divide
- Not all employees globally have equal IP assignments (as BEIPA is written to be catch-all except for specific state exceptions and employee negotiated amendments).

**Comment by mlinksva** [comment]
It's common (universal?) for employee IP agreements to cover copyright and patent. A violation of the idea-expression divide happens when someone tries to use a copyright to exercise patent-like control over an idea.
